x-logging: &default-logging
    driver: json-file
    options:
        max-size: "10m"
        max-file: "3"
services:
    skiserviceapi:
        image: ghcr.io/simonloeffler1993/skiserviceapi:latest
        logging: *default-logging
        container_name: skiserviceapi
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - SMTP_SERVER=${SMTP_SERVER}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
            - EMAIL_FROM=${EMAIL_FROM}
            - HOST=${HOST}
            - LEXWARE_APIKEY=${LEXWARE_APIKEY}
        depends_on:
            mariadb:
                condition: service_healthy
        restart: unless-stopped

    kundenterminal:
        image: ghcr.io/simonloeffler1993/ski-kunden-dialog:latest
        logging: *default-logging
        container_name: kundenterminal
        ports:
            - "3000:3000"
        depends_on:
            - skiserviceapi
        environment:
            - BACKEND_URL=${BACKEND_URL}
        restart: unless-stopped

    skiservicecenter:
        image: ghcr.io/simonloeffler1993/skiservice-center:latest
        logging: *default-logging
        container_name: skiservicecenter
        ports:
            - "3001:3000"
        depends_on:
            - skiserviceapi
        environment:
            - BACKEND_URL=${BACKEND_URL}
        restart: unless-stopped

    mariadb:
        image: mariadb:11
        container_name: mariadb
        logging: *default-logging
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - mariadb_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    # Optional: Databasus service fuer Datenbank Sicherung und Wiederherstellung
    databasus:
        container_name: databasus
        logging: *default-logging
        image: databasus/databasus:latest
        ports:
            - "4005:4005"
        volumes:
            - /volume1/docker/databasus/data:/databasus-data
        restart: unless-stopped

    # Optional: phpMyAdmin service fuer Datenbank Verwaltung
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        logging: *default-logging
        ports:
            - "${PMA_PORT}:80"
        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
        depends_on:
            - mariadb
        restart: unless-stopped

volumes:
    mariadb_data:
