"""initial schema

Revision ID: 1ff45b6d6fb7
Revises: 
Create Date: 2026-09-07 22:07:00.225566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff45b6d6fb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auftragnummer',
    sa.Column('NeuNr', sa.Integer(), nullable=False),
    sa.Column('Jahr', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('NeuNr')
    )
    op.create_table('dienstleistung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Service', sa.String(length=50), nullable=False),
    sa.Column('Preis', sa.String(length=50), nullable=False),
    sa.Column('Check', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postleitzahl',
    sa.Column('Postlz', sa.Integer(), nullable=False),
    sa.Column('Ort', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('Postlz')
    )
    op.create_table('quittungen',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('AnzAuftrag', sa.Integer(), nullable=True),
    sa.Column('AnzVerleih', sa.Integer(), nullable=True),
    sa.Column('Saison_ID', sa.Integer(), nullable=False),
    sa.Column('Bezahlt_Am', sa.Date(), nullable=True),
    sa.Column('Erstellt_Am', sa.Date(), nullable=False),
    sa.Column('Ueberweisung', sa.Boolean(), nullable=True),
    sa.Column('Bezahlt', sa.Boolean(), nullable=True),
    sa.Column('BuchhaltungSync', sa.Boolean(), nullable=True),
    sa.Column('LexID', sa.String(length=150), nullable=False),
    sa.Column('NurExtern', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('saisons',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Start', sa.Date(), nullable=False),
    sa.Column('Ende', sa.Date(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Verwendet', sa.Integer(), nullable=False),
    sa.Column('SaisonVerleihNummer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('saisonverleihpreise',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Bezeichnung', sa.String(length=50), nullable=False),
    sa.Column('Preis', sa.Double(), nullable=False),
    sa.Column('vonL', sa.Integer(), nullable=True),
    sa.Column('bisL', sa.Integer(), nullable=True),
    sa.Column('SkiArt_ID', sa.Integer(), nullable=True),
    sa.Column('inaktiv', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('skiart',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Art', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('verleihschuhhersteller',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('verleihskihersteller',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('verleihstocke',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Bezeichnung', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('adresse',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Nachname', sa.String(length=20), nullable=True),
    sa.Column('Vorname', sa.String(length=20), nullable=True),
    sa.Column('Anrede', sa.String(length=1), nullable=True),
    sa.Column('Strasse', sa.String(length=250), nullable=True),
    sa.Column('Plz', sa.Integer(), nullable=True),
    sa.Column('Tel', sa.String(length=50), nullable=True),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('Tel1', sa.String(length=50), nullable=True),
    sa.Column('Tel2', sa.String(length=50), nullable=True),
    sa.Column('Email1', sa.String(length=50), nullable=True),
    sa.Column('Email2', sa.String(length=50), nullable=True),
    sa.Column('AusweisNr', sa.String(length=15), nullable=True),
    sa.Column('BDay', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['Plz'], ['postleitzahl.Postlz'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('verleihschuhmodell',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Modell', sa.String(length=100), nullable=True),
    sa.Column('Jugend', sa.Integer(), nullable=True),
    sa.Column('Hersteller_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Hersteller_ID'], ['verleihschuhhersteller.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('verleihskimodell',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Modell', sa.String(length=100), nullable=True),
    sa.Column('Art_ID', sa.Integer(), nullable=True),
    sa.Column('Hersteller_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Art_ID'], ['skiart.ID'], ),
    sa.ForeignKeyConstraint(['Hersteller_ID'], ['verleihskihersteller.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('auftraege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Kunden_ID', sa.Integer(), nullable=False),
    sa.Column('Start_Date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Ende_Date', sa.String(length=150), nullable=True),
    sa.Column('Wie', sa.String(length=1), nullable=True),
    sa.Column('A_Ski', sa.String(length=11), nullable=True),
    sa.Column('Ettiket', sa.String(length=5), nullable=True),
    sa.Column('ZU', sa.String(length=10), nullable=False),
    sa.Column('Fertig_Date', sa.String(length=10), nullable=True),
    sa.Column('Abhol_Date', sa.String(length=10), nullable=True),
    sa.Column('Anzahlung', sa.String(length=11), nullable=True),
    sa.Column('Bezahlt', sa.String(length=11), nullable=False),
    sa.Column('Bezahlt_Am', sa.Date(), nullable=True),
    sa.Column('Benachrichtigt', sa.String(length=10), nullable=False),
    sa.Column('Abgerechnet', sa.Integer(), nullable=True),
    sa.Column('Uberweisung', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=15), nullable=False),
    sa.Column('AnzLeih', sa.Integer(), nullable=True),
    sa.Column('Rabat', sa.Double(), nullable=True),
    sa.Column('RabatName', sa.String(length=25), nullable=True),
    sa.Column('RabatWaerung', sa.Integer(), nullable=True),
    sa.Column('Leih_Versicherung', sa.Integer(), nullable=True),
    sa.Column('QuittungID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Kunden_ID'], ['adresse.ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eigenschuh',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Modell_ID', sa.Integer(), nullable=True),
    sa.Column('Groese', sa.Double(), nullable=True),
    sa.Column('Saison', sa.String(length=20), nullable=True),
    sa.Column('VK', sa.Double(), nullable=True),
    sa.Column('EK', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['Modell_ID'], ['verleihschuhmodell.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('eigenski',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Modell_ID', sa.Integer(), nullable=True),
    sa.Column('Laenge', sa.Integer(), nullable=True),
    sa.Column('VK', sa.Double(), nullable=True),
    sa.Column('EK', sa.Double(), nullable=True),
    sa.Column('Saison', sa.String(length=20), nullable=True),
    sa.Column('SkiNr', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['Modell_ID'], ['verleihskimodell.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('SkiNr')
    )
    op.create_table('saisonverleih',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Kunde_ID', sa.Integer(), nullable=True),
    sa.Column('Ueberweisung', sa.Boolean(), nullable=True),
    sa.Column('Bezahlt', sa.Boolean(), nullable=True),
    sa.Column('Bezahlt_Am', sa.Date(), nullable=True),
    sa.Column('Zurueck', sa.Integer(), nullable=True),
    sa.Column('Zurueck_Am', sa.Date(), nullable=True),
    sa.Column('Bemerkung', sa.String(length=500), nullable=True),
    sa.Column('Saison_ID', sa.Integer(), nullable=True),
    sa.Column('Abgerechnet', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Start_Am', sa.Date(), nullable=False),
    sa.Column('QuittungID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Kunde_ID'], ['adresse.ID'], ),
    sa.ForeignKeyConstraint(['Saison_ID'], ['saisons.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('saisonverleihmaterial',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('SaisonVerlei_ID', sa.Integer(), nullable=True),
    sa.Column('skinr', sa.String(length=50), nullable=True),
    sa.Column('schuhnr', sa.Integer(), nullable=True),
    sa.Column('stockbez_ID', sa.Integer(), nullable=True),
    sa.Column('stocklaenge', sa.Integer(), nullable=True),
    sa.Column('Preis', sa.Double(), nullable=False),
    sa.Column('SkiFahrerName', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['SaisonVerlei_ID'], ['saisonverleih.ID'], ),
    sa.ForeignKeyConstraint(['schuhnr'], ['eigenschuh.ID'], ),
    sa.ForeignKeyConstraint(['skinr'], ['eigenski.SkiNr'], ),
    sa.ForeignKeyConstraint(['stockbez_ID'], ['verleihstocke.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('ski',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Auftrag_ID', sa.Integer(), nullable=False),
    sa.Column('Service', sa.Text(), nullable=False),
    sa.Column('Preis', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.Column('komentar', sa.Text(), nullable=True),
    sa.Column('dabei', sa.Integer(), nullable=True),
    sa.Column('Fertig_Date', sa.String(length=10), nullable=True),
    sa.Column('BindungID', sa.Integer(), nullable=False),
    sa.Column('BindungCheck', sa.Boolean(), nullable=False),
    sa.Column('BindungPreis', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Name', sa.String(length=15), nullable=True),
    sa.Column('Band', sa.Integer(), nullable=False),
    sa.Column('Sack', sa.Integer(), nullable=False),
    sa.Column('BindungStatus', sa.Boolean(), nullable=False),
    sa.Column('Gepueft', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Auftrag_ID'], ['auftraege.id'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ski')
    op.drop_table('saisonverleihmaterial')
    op.drop_table('saisonverleih')
    op.drop_table('eigenski')
    op.drop_table('eigenschuh')
    op.drop_table('auftraege')
    op.drop_table('verleihskimodell')
    op.drop_table('verleihschuhmodell')
    op.drop_table('adresse')
    op.drop_table('verleihstocke')
    op.drop_table('verleihskihersteller')
    op.drop_table('verleihschuhhersteller')
    op.drop_table('skiart')
    op.drop_table('saisonverleihpreise')
    op.drop_table('saisons')
    op.drop_table('quittungen')
    op.drop_table('postleitzahl')
    op.drop_table('dienstleistung')
    op.drop_table('auftragnummer')
    # ### end Alembic commands ###
